# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'
variables:
  BuildConfiguration: Release
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetAuthenticate@1
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/LeetCode.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/LeetCode.csproj'
    arguments: '-c $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/LeetCode.csproj'
    nobuild: true
    versioningScheme: 'byBuildNumber'