# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetAuthenticate@1
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/LeetCode.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/LeetCode.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/LeetCode.sln'
    versioningScheme: 'byBuildNumber'