# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetAuthenticate@1
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'd4803183-acd6-4a74-92e6-ed140af41fe6'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/LeetCode.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/LeetCode.csproj'
    versioningScheme: 'byBuildNumber'