version: '3.4'

services:
  leetcode:
    image: leetcode:dev
    container_name: LeetCode
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "LeetCode"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/rkholov/Desktop/BestDotnetTraining/GitHubRepo/LeetCodeWithCSharp/LeetCode:/app
      - /Users/rkholov/Desktop/BestDotnetTraining/GitHubRepo/LeetCodeWithCSharp:/src
      - /Users/rkholov/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/rkholov/.nuget/packages/:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net8.0/LeetCode.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true